# Font
font_family JetBrainsMono Nerd Font Mono
font_size 19.5

# Colors
# Tokyo Night (najbliže WezTerm color_scheme)
background #000000
foreground #c0caf5

selection_background #33467c
selection_foreground #c0caf5

# Window
hide_window_decorations no
window_padding_width 0 0 0 10

# Opacity
background_opacity 0.9

# Tabs
tab_bar_style hidden

# Close confirmation
confirm_os_window_close 0

# Mouse
# kitty nema direktan "hide_mouse_cursor_when_typing=false"
# ovo osigurava da kursor ostane vidljiv
cursor_shape block

# Start tmux
# shell tmux
