#!/bin/bash

CONFIG_FILE="$HOME/.config/.bootstrap.conf"

if [[ ! -f "$CONFIG_FILE" ]]; then
  while true; do
    read -rp "Is this your personal PC? (y/n): " answer
    case "$answer" in
    [Yy]*)
      IS_PERSONAL_PC=true
      break
      ;;
    [Nn]*)
      IS_PERSONAL_PC=false
      break
      ;;
    *)
      echo "Please answer y or n."
      ;;
    esac
  done

  echo "IS_PERSONAL_PC=$IS_PERSONAL_PC" >"$CONFIG_FILE"
fi

# Load the saved value
source "$CONFIG_FILE"

needs_reboot=0

sudo -v

pacman -Qi ttf-jetbrains-mono-nerd &>/dev/null || sudo pacman -S --noconfirm ttf-jetbrains-mono-nerd
pacman -Qi otf-font-awesome &>/dev/null || sudo pacman -S --noconfirm otf-font-awesome

pacman -Qi git &>/dev/null || sudo pacman -S --noconfirm git
pacman -Qi base-devel &>/dev/null || sudo pacman -S --noconfirm base-devel
pacman -Qi less &>/dev/null || sudo pacman -S --noconfirm less
pacman -Qi unzip &>/dev/null || sudo pacman -S --noconfirm unzip
pacman -Qi wofi &>/dev/null && sudo pacman -R --noconfirm wofi
pacman -Qi rofi &>/dev/null || sudo pacman -S --noconfirm rofi
pacman -Qi fd &>/dev/null || sudo pacman -S --noconfirm fd
pacman -Qi fzf &>/dev/null || sudo pacman -S --noconfirm fzf
pacman -Qi lsd &>/dev/null || sudo pacman -S --noconfirm lsd
pacman -Qi zoxide &>/dev/null || sudo pacman -S --noconfirm zoxide
pacman -Qi playerctl &>/dev/null || sudo pacman -S --noconfirm playerctl
pacman -Qi brightnessctl &>/dev/null || sudo pacman -S --noconfirm brightnessctl
yay -Qi pwvucontrol &>/dev/null || yay -S --noconfirm pwvucontrol

pacman -Qi grim &>/dev/null || sudo pacman -S --noconfirm grim
pacman -Qi slurp &>/dev/null || sudo pacman -S --noconfirm slurp
pacman -Qi hyprshot &>/dev/null || sudo pacman -S --noconfirm hyprshot
pacman -Qi hyprpicker &>/dev/null || sudo pacman -S --noconfirm hyprpicker
pacman -Qi hyprlock &>/dev/null || sudo pacman -S --noconfirm hyprlock

pacman -Qi hypridle &>/dev/null || sudo pacman -S --noconfirm hypridle
systemctl --user enable --now hypridle.service

pacman -Qi nautilus &>/dev/null || sudo pacman -S --noconfirm nautilus
pacman -Qi dolphin &>/dev/null && sudo pacman -R --noconfirm dolphin

pacman -Qi udisks2 &>/dev/null || sudo pacman -S --noconfirm udisks2
pacman -Qi hyprpolkitagent &>/dev/null || sudo pacman -S --noconfirm hyprpolkitagent

# ZSH
# ------------------------------------------------------------------
pacman -Qi zsh &>/dev/null || sudo pacman -S --needed --noconfirm zsh

zsh=$(which zsh)

if [ "$SHELL" != "$zsh" ]; then
  if ! grep -qxF "$zsh" /etc/shells; then
    echo "$zsh" | sudo tee -a /etc/shells >/dev/null
  fi

  chsh -s "$zsh"
  needs_reboot=1
fi

# Oh-My-Zsh
[ -d "$HOME/.oh-my-zsh" ] || (export KEEP_ZSHRC=yes && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)")
# ------------------------------------------------------------------

pacman -Qi imagemagick &>/dev/null || sudo pacman -S --noconfirm imagemagick
pacman -Qi kitty &>/dev/null || sudo pacman -S --noconfirm kitty
pacman -Qi tmux &>/dev/null || sudo pacman -S --noconfirm tmux
pacman -Qi bitwarden &>/dev/null || sudo pacman -S --noconfirm bitwarden
pacman -Qi obsidian &>/dev/null || sudo pacman -S --noconfirm obsidian
pacman -Qi pipewire-pulse &>/dev/null || sudo pacman -S --noconfirm pipewire-pulse
pacman -Qi obs-studio &>/dev/null || sudo pacman -S --noconfirm obs-studio

pacman -Qi lua &>/dev/null || sudo pacman -S --noconfirm lua
pacman -Qi lua51 &>/dev/null || sudo pacman -S --noconfirm lua51
pacman -Qi luarocks &>/dev/null || sudo pacman -S --noconfirm luarocks
pacman -Qi tree-sitter-cli &>/dev/null || sudo pacman -S --noconfirm tree-sitter-cli
pacman -Qi neovim &>/dev/null || sudo pacman -S --noconfirm neovim

pacman -Qi go &>/dev/null || sudo pacman -S --noconfirm go
pacman -Qi nodejs &>/dev/null || sudo pacman -S --noconfirm nodejs
pacman -Qi npm &>/dev/null || sudo pacman -S --noconfirm npm

install_yay() {
  tmpdir=$(mktemp -d) &&
    git clone https://aur.archlinux.org/yay-bin.git "$tmpdir/yay-bin" &&
    (
      cd "$tmpdir/yay-bin" &&
        makepkg -si
    )
  rm -rf "$tmpdir"
}

command -v yay &>/dev/null || install_yay

yay -Qi pureref &>/dev/null || yay -S --noconfirm pureref
yay -Qi zen-browser-bin &>/dev/null || yay -S --noconfirm zen-browser-bin
yay -Qi google-chrome &>/dev/null || yay -S --noconfirm google-chrome
yay -Qi slack-desktop &>/dev/null || yay -S --noconfirm slack-desktop

pacman -Qi glib2 &>/dev/null || sudo pacman -S --noconfirm glib2
pacman -Qi gnome-themes-extra &>/dev/null || sudo pacman -S --noconfirm gnome-themes-extra
yay -Qi adwaita-qt6-git &>/dev/null || yay -S --noconfirm adwaita-qt6-git

gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

pacman -Qi hyprpaper &>/dev/null || sudo pacman -S --noconfirm hyprpaper
systemctl --user enable --now hyprpaper.service

pacman -Qi wl-clipboard &>/dev/null || sudo pacman -S --noconfirm wl-clipboard
pacman -Qi cliphist &>/dev/null || sudo pacman -S --noconfirm cliphist
sudo chmod +x ~/.config/rofi/pickers/clipboard_history.sh

pacman -Qi waybar &>/dev/null || sudo pacman -S --noconfirm waybar
systemctl --user enable --now waybar.service

sudo chmod +x ~/.config/rofi/pickers/confirm.sh
sudo chmod +x ~/.config/rofi/pickers/power_menu.sh
sudo chmod +x ~/.config/rofi/pickers/app_launcher.sh

pacman -Qi git-delta &>/dev/null || sudo pacman -S --noconfirm git-delta
git config --global core.pager delta
git config --global interactive.diffFilter 'delta --color-only'
git config --global delta.navigate true
git config --global delta.dark true # or `delta.light true`, or omit for auto-detection
git config --global merge.conflictStyle zdiff3

yay -Qi localsend-bin &>/dev/null || yay -S --noconfirm localsend-bin

if [[ -v IS_PERSONAL_PC && "$IS_PERSONAL_PC" == "true" ]]; then
  pacman -Qi meson &>/dev/null || sudo pacman -S --noconfirm meson
else
  pacman -Qi dotnet-sdk-8.0 &>/dev/null || sudo pacman -S --noconfirm dotnet-sdk-8.0
fi

sudo chmod +x ~/.config/ftwa/excalidraw.sh && ~/.config/ftwa/excalidraw.sh
sudo chmod +x ~/.config/ftwa/youtube-music.sh && ~/.config/ftwa/youtube-music.sh
sudo chmod +x ~/.config/ftwa/gmail.sh && ~/.config/ftwa/gmail.sh

(
  cd "$HOME" && yadm submodule update --recursive --init
)

if [ "$needs_reboot" = true ]; then
  read -r -p "You need to reboot PC(y/n): " x
  [ "$x" = y ] && reboot
fi
